vyos_config_block and documentation
Foltik/terraform-provider-vyos pull request #2
Opened 2021-10-15 13:15 UTC by thomasfinstad

This PR adds the option to configure multiple attributes at the same time in a configuration block with the new **vyos_config_block** resource before vyos runs the commit command, opening up for more configurations to be used via this provider.

There is also a new doc layout that is supposedly compatible with terraform registry, with information quickly skimmed from this page: https://www.terraform.io/docs/registry/providers/docs.html

2021-10-15 15:23 UTC, foltik commented
Awesome, thanks for the contribution! I'll add some more docs for the rest of the resources, then test and merge ASAP.

2021-10-16 05:54 UTC, thomasfinstad commented
Thanks for helping me cleanup typeos and such :1st_place_medal: 

I might create some more resources after a while, but with this and your config resource I think most of vyos should be configurable, but someone I know did point out that it would be nice to not have to know the vyos config in and out to use terraform for it.

I only wish there was an API to push/pull/delete scripts and other files on the box as I need a vrrp script, I added in a request for that just now: https://phabricator.vyos.net/T3909 though I think the client would need to implement that if it gets implemented

2021-10-16 14:30 UTC, foltik requested changes
Of course! I left a few comments as well; forgot to submit them previously.

2021-10-16 14:30 UTC, foltik commented on vyos/resource_config_block.go
> +			delete(configs, attr)
`c.SetTree` supports nested maps and expands spaces in keys, so something like this should work out of the box:

```hcl
configs = {
  # ...

  "destination group port-group": "Jedi" 
  # or
  "destination group": {
    "port-group": "Jedi"
    # ...
  }
}
```

So maybe allow nesting and keys to contain spaces?

2021-10-16 14:30 UTC, foltik commented on vyos/resource_config_block.go
> +				Type:             schema.TypeMap,
We should specify [Elem](https://www.terraform.io/docs/extend/schemas/schema-types.html#typemap) to set type constraints for the map values.

2021-10-16 17:03 UTC, thomasfinstad commented on vyos/resource_config_block.go
> +			delete(configs, attr)
I was learning golang and terraform provider  coding on the fly and could not make a truly free form map to work as a input variable to the provider. It wanted a flat map, and the blocking of spaces on the keys are mostly a safe guard to keep people from making weird hacky ways around it being a si gle level block (due to the flat map restriction), and is why I picked that style of example to show how to do the next "layer" down correctly, as the lower block should be destroyed first when you run terraform destroy.

If you know how to have a multi level nested config block that is free form I think that would be the way to go, and what I wanted initially, but was unable to make it work.

2021-10-16 17:06 UTC, thomasfinstad commented on vyos/resource_config_block.go
> +				Type:             schema.TypeMap,
Good point, I guess string and number would be all that should be allowed. I will look into this tomorrow if I can find time.

2021-10-16 17:07 UTC, thomasfinstad commented
Stupid mobile app opened the close button right under my thumb, oops 😅

2021-10-24 08:05 UTC, thomasfinstad commented on vyos/resource_config_block.go
> +				Type:             schema.TypeMap,
The new commit https://github.com/Foltik/terraform-provider-vyos/pull/2/commits/0b8150c88d2bf97528bef874d584f74a2a1ed7c2 adds Elem to the config block resource.

2021-10-24 08:11 UTC, thomasfinstad commented on vyos/resource_config_block.go
> +			delete(configs, attr)
I think I get what you mean now, but I still think it is better to have separate resources that depends on each other than to promote "hacking" the resource in this manor. If there are situations where people get stuck because they need a multi _layer_ commit for the commit to be valid then maybe this would require another look.

The best would still be if we could use a "freeform" map that could recurse inwards with several blocks, but in time my hope is that this resource and your config resource will just be a backup for when a proper resource has not been created since with some good helper functions I think we can very easily speed up the creation of new resources.

2021-10-25 16:59 UTC, foltik commented on vyos/resource_config_block.go
> +			delete(configs, attr)
Right, I'll take another look at adding that functionality later.

2021-10-25 17:08 UTC, merged

2021-10-27 13:03 UTC, thomasfinstad commented on vyos/resource_config_block.go
> +			delete(configs, attr)
Sounds good, I hope to have the time to help adding more stuff very soon but no promises.